### Reading Data From Different Sources

You're reading JSON data into a Pandas DataFrame.

1.  **`import pandas as pd`**: Imports the Pandas library, giving you tools for working with DataFrames.
2.  **`from io import StringIO`**: Imports `StringIO`, which lets you treat a string like a file.
3.  **`Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'`**: This is a JSON string containing information about an employee. Notice `job_profile` is a list containing a dictionary.
4.  **`df=pd.read_json(StringIO(Data))`**:
    * `StringIO(Data)`: Makes the JSON string behave like a readable file.
    * `pd.read_json(...)`: Reads the JSON data from the "file" and creates a Pandas DataFrame named `df`.

In short, this code takes a JSON string and turns it into a table-like structure (DataFrame) that you can easily work with using Pandas. The `job_profile` will likely be a column containing lists of dictionaries.


`StringIO` is a class in Python's `io` module that allows you to treat a string as a file-like object.

`StringIO` provides a convenient way to work with string data as if it were a file, especially when used with libraries like pandas that have functions designed to read from files or file-like objects. It avoids the need for temporary file creation and can make your code cleaner and more efficient when dealing with in-memory string data. Using `StringIO` ensures that you are providing the input in the format that `pd.read_json()` expects for reading from a string.

In [1]:
2

2

In [2]:
import pandas as pd
from io import StringIO

Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
print(type(Data))
df=pd.read_json(StringIO(Data))

<class 'str'>

In [3]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

`df.to_json()` converts your entire Pandas DataFrame `df` into a JSON (JavaScript Object Notation) string. This format is commonly used for data transmission and storage because it's lightweight and readable by many programming languages.

In [4]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [5]:
# display the docstring for the to_json() function, which clearly lists and describes 
# all the possible values for the orient parameter.
help(pd.DataFrame.to_json)

Help on function to_json in module pandas.core.generic:

to_json(
    self,
    path_or_buf: 'FilePath | WriteBuffer[bytes] | WriteBuffer[str] | None' = None,
    *,
    orient: "Literal['split', 'records', 'index', 'table', 'columns', 'values'] | None" = None,
    date_format: 'str | None' = None,
    double_precision: 'int' = 10,
    force_ascii: 'bool' = True,
    date_unit: 'TimeUnit' = 'ms',
    default_handler: 'Callable[[Any], JSONSerializable] | None' = None,
    lines: 'bool' = False,
    compression: 'CompressionOptions' = 'infer',
    index: 'bool | None' = None,
    indent: 'int | None' = None,
    storage_options: 'StorageOptions | None' = None,
    mode: "Literal['a', 'w']" = 'w'
) -> 'str | None'
    Convert the object to a JSON string.

    Note NaN's and None will be converted to null and datetime objects
    will be converted to UNIX timestamps.

    Parameters
    ----------
    path_or_buf : str, path object, file-like object, or None, default None
        String, path object (implementing os.PathLike[str]), or file-like
        object implementing a write() function. If None, the result is
        returned as a string.
    orient : str
        Indication of expected JSON string format.

        * Series:

            - default is 'index'
            - allowed values are: {'split', 'records', 'index', 'table'}.

        * DataFrame:

            - default is 'columns'
            - allowed values are: {'split', 'records', 'index', 'columns',
              'values', 'table'}.

        * The format of the JSON string:

            - 'split' : dict like {'index' -> [index], 'columns' -> [columns],
              'data' -> [values]}
            - 'records' : list like [{column -> value}, ... , {column -> value}]
            - 'index' : dict like {index -> {column -> value}}
            - 'columns' : dict like {column -> {index -> value}}
            - 'values' : just the values array
            - 'table' : dict like {'schema': {schema}, 'data': {data}}

            Describing the data, where data component is like ``orient='records'``.

    date_format : {None, 'epoch', 'iso'}
        Type of date conversion. 'epoch' = epoch milliseconds,
        'iso' = ISO8601. The default depends on the `orient`. For
        ``orient='table'``, the default is 'iso'. For all other orients,
        the default is 'epoch'.

        .. deprecated:: 3.0.0
            'epoch' date format is deprecated and will be removed in a future
            version, please use 'iso' instead.

    double_precision : int, default 10
        The number of decimal places to use when encoding
        floating point values. The possible maximal value is 15.
        Passing double_precision greater than 15 will raise a ValueError.
    force_ascii : bool, default True
        Force encoded string to be ASCII.
    date_unit : str, default 'ms' (milliseconds)
        The time unit to encode to, governs timestamp and ISO8601
        precision.  One of 's', 'ms', 'us', 'ns' for second, millisecond,
        microsecond, and nanosecond respectively.
    default_handler : callable, default None
        Handler to call if object cannot otherwise be converted to a
        suitable format for JSON. Should receive a single argument which is
        the object to convert and return a serialisable object.
    lines : bool, default False
        If 'orient' is 'records' write out line-delimited json format. Will
        throw ValueError if incorrect 'orient' since others are not
        list-like.

    compression : str or dict, default 'infer'
        For on-the-fly compression of the output data. If 'infer' and
        'path_or_buf' is path-like, then detect compression from the following
        extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        Set to ``None`` for no compression.
        Can also be a dict with key ``'method'`` set to one of
        {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdCompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for faster compression and
        to create a reproducible gzip archive:
        ``compression={'method': 'gzip', 'compresslevel': 1, 'mtime': 1}``.

    index : bool or None, default None
        The index is only used when 'orient' is 'split', 'index', 'column',
        or 'table'. Of these, 'index' and 'column' do not support
        `index=False`. The string 'index' as a column name with empty :class:`Index`
        or if it is 'index' will raise a ``ValueError``.

    indent : int, optional
       Length of whitespace used to indent each record.

    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    mode : str, default 'w' (writing)
        Specify the IO mode for output when supplying a path_or_buf.
        Accepted args are 'w' (writing) and 'a' (append) only.
        mode='a' is only supported when lines is True and orient is 'records'.

    Returns
    -------
    None or str
        If path_or_buf is None, returns the resulting json format as a
        string. Otherwise returns None.

    See Also
    --------
    read_json : Convert a JSON string to pandas object.

    Notes
    -----
    The behavior of ``indent=0`` varies from the stdlib, which does not
    indent the output but does insert newlines. Currently, ``indent=0``
    and the default ``indent=None`` are equivalent in pandas, though this
    may change in a future release.

    ``orient='table'`` contains a 'pandas_version' field under 'schema'.
    This stores the version of `pandas` used in the latest revision of the
    schema.

    Examples
    --------
    >>> from json import loads, dumps
    >>> df = pd.DataFrame(
    ...     [["a", "b"], ["c", "d"]],
    ...     index=["row 1", "row 2"],
    ...     columns=["col 1", "col 2"],
    ... )

    >>> result = df.to_json(orient="split")
    >>> parsed = loads(result)
    >>> dumps(parsed, indent=4)  # doctest: +SKIP
    {
        "columns": [
            "col 1",
            "col 2"
        ],
        "index": [
            "row 1",
            "row 2"
        ],
        "data": [
            [
                "a",
                "b"
            ],
            [
                "c",
                "d"
            ]
        ]
    }

    Encoding/decoding a Dataframe using ``'records'`` formatted JSON.
    Note that index labels are not preserved with this encoding.

    >>> result = df.to_json(orient="records")
    >>> parsed = loads(result)
    >>> dumps(parsed, indent=4)  # doctest: +SKIP
    [
        {
            "col 1": "a",
            "col 2": "b"
        },
        {
            "col 1": "c",
            "col 2": "d"
        }
    ]

    Encoding/decoding a Dataframe using ``'index'`` formatted JSON:

    >>> result = df.to_json(orient="index")
    >>> parsed = loads(result)
    >>> dumps(parsed, indent=4)  # doctest: +SKIP
    {
        "row 1": {
            "col 1": "a",
            "col 2": "b"
        },
        "row 2": {
            "col 1": "c",
            "col 2": "d"
        }
    }

    Encoding/decoding a Dataframe using ``'columns'`` formatted JSON:

    >>> result = df.to_json(orient="columns")
    >>> parsed = loads(result)
    >>> dumps(parsed, indent=4)  # doctest: +SKIP
    {
        "col 1": {
            "row 1": "a",
            "row 2": "c"
        },
        "col 2": {
            "row 1": "b",
            "row 2": "d"
        }
    }

    Encoding/decoding a Dataframe using ``'values'`` formatted JSON:

    >>> result = df.to_json(orient="values")
    >>> parsed = loads(result)
    >>> dumps(parsed, indent=4)  # doctest: +SKIP
    [
        [
            "a",
            "b"
        ],
        [
            "c",
            "d"
        ]
    ]

    Encoding with Table Schema:

    >>> result = df.to_json(orient="table")
    >>> parsed = loads(result)
    >>> dumps(parsed, indent=4)  # doctest: +SKIP
    {
        "schema": {
            "fields": [
                {
                    "name": "index",
                    "type": "string"
                },
                {
                    "name": "col 1",
                    "type": "string"
                },
                {
                    "name": "col 2",
                    "type": "string"
                }
            ],
            "primaryKey": [
                "index"
            ],
            "pandas_version": "1.4.0"
        },
        "data": [
            {
                "index": "row 1",
                "col 1": "a",
                "col 2": "b"
            },
            {
                "index": "row 2",
                "col 1": "c",
                "col 2": "d"
            }
        ]
    }

`df.to_json(orient='index')` converts your DataFrame `df` into a JSON string. The `orient='index'` part means each **row** of your DataFrame becomes a separate JSON object. The keys of these objects are the **index labels** of the rows, and the values are dictionaries containing the column names and their corresponding row values.

**Example:**

If your DataFrame `df` looks like this:

```
   col1  col2
a     1     3
b     2     4
```

Then `df.to_json(orient='index')` would produce a JSON string like this:

```json
{"a":{"col1":1,"col2":3},"b":{"col1":2,"col2":4}}
```
Reference: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html

In [17]:
df.to_json(orient='index')
# df.to_json(orient='index')[2]

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

`df.to_json(orient='records')` converts your DataFrame `df` into a JSON string where each row becomes a separate JSON object (a dictionary). The `records` orientation arranges the data as a list of these row-objects.

**Short, simple code example:**

```python
import pandas as pd

data = {'col1': [1, 2], 'col2': ['a', 'b']}
df = pd.DataFrame(data)

json_output = df.to_json(orient='records')
print(json_output)
```

**Output:**

```json
[{"col1":1,"col2":"a"},{"col1":2,"col2":"b"}]
```

Each dictionary in the list represents a row from your DataFrame, with keys as column names and values as the row data.

In [25]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

## Read Data from Internet URLs

In [26]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
# df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")

In [27]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [27]:
# Write object to a comma-separated values (csv) file.
df.to_csv("wine.csv")

In [28]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\kkapil\appdata\local\anaconda3\lib\site-packages (5.3.0)

In [29]:
!pip install html5lib
!pip install beautifulsoup4

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\kkapil\appdata\local\anaconda3\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in c:\users\kkapil\appdata\local\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Requirement already satisfied: beautifulsoup4 in c:\users\kkapil\appdata\local\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\kkapil\appdata\local\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)

In [28]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url)

In [29]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [34]:
import pandas as pd
import requests
import io

url = "https://en.wikipedia.org/wiki/Mobile_country_code"
headers = {"User-Agent": "Mozilla/5.0"}

# Get the data from the web
response = requests.get(url, headers=headers)

# Use io.StringIO to feed the response text into pandas
df = pd.read_html(io.StringIO(response.text), match="Country")[0]

In [35]:
df

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [34]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\kkapil\appdata\local\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\kkapil\appdata\local\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [36]:
df_excel=pd.read_excel('data.xlsx')
df_excel

    Name  Age
0  Karan   32
1   Jack   34
2   John   31

`df_excel.to_pickle('df_excel')` saves the pandas DataFrame named `df_excel` to a file named 'df_excel' in the pickle format.

**In essence:**

It performs **serialization** of the DataFrame into a binary file, preserving its structure and data types. You can later load it back into a DataFrame using `pd.read_pickle('df_excel')`.

**Use it when:**

* You want to save a DataFrame for **faster reading** in a future Python session compared to text-based formats like CSV.
* You need to **preserve the data types** and structure of the DataFrame exactly as they are.

The resulting file 'df_excel' will be in a binary format, not easily human-readable.

In [37]:
df_excel.to_pickle('df_excel') # file saved but not direcly readable

In [38]:
# read pickle file
pd.read_pickle('df_excel')

    Name  Age
0  Karan   32
1   Jack   34
2   John   31